readme.md 수정
BFY-PDCT/BFYBOT pull request #28
Opened 2021-11-26 13:00 UTC by mihyun-note

안녕하세요 파랭이봇 정말 잘 사용하고있습니다!
이렇게 좋은 봇이 더욱 더 많이 사용됐으면 좋겠다는 마음이 들어서  
readme.md 파일을 조금 수정해보았습니다! 
괜찮으시면 확인 부탁드려요 👍

2021-11-26 19:51 UTC, jhleekr commented on README.md
> +![00](https://user-images.githubusercontent.com/83504363/143582696-f57343f9-66f2-4022-bdd2-36787fb3c457.gif)
gif파일 저희 서버에 업로드하여 링크 변경할 예정입니다 :)

2021-11-26 19:51 UTC, jhleekr commented on README.md
> +![01](https://user-images.githubusercontent.com/83504363/143582682-e6bda2b6-8684-488c-a27c-d020292da9ae.gif)
이 gif파일 또한 저희 서버에 업로드하여 링크 변경할 예정입니다 :)

2021-11-26 19:53 UTC, jhleekr reviewed
도움 주셔서 감사드립니다! 파일 링크 변경한 뒤 merge할 예정입니다.

2021-11-27 04:25 UTC, jhleekr requested changes
두 링크
https://www.bfy.kr/files/bfybotgif1.gif
https://www.bfy.kr/files/bfybotgif2.gif
로 변경 부탁드립니다 :)

2021-11-27 05:01 UTC, mihyun-note commented
답변 감사합니다! 두 gif 파일 전부 남겨주신 링크로 변경했습니다 :)

2021-11-27 05:03 UTC, jhleekr commented
전달이 잘못된 것 같네요 죄송합니다 ㅠㅠ
![00](https://www.bfy.kr/files/bfybotgif1.gif)
![01](https://www.bfy.kr/files/bfybotgif2.gif)
이렇게 변경해주시면 김사드리겠습니다!

2021-11-27 05:04 UTC, jhleekr commented
`![00](https://www.bfy.kr/files/bfybotgif1.gif)`
`![01](https://www.bfy.kr/files/bfybotgif2.gif)`
이렇게 작성해주시면 될 것 같아요!

2021-11-27 05:10 UTC, mihyun-note commented
복붙이 잘못돼서...죄송합니다 ㅜ.ㅜ 수정했습니다!!

2021-11-27 05:15 UTC, jhleekr approved these changes
완료된 것 같습니다 기여 감사드립니다 :)

2021-11-27 05:18 UTC, merged